// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scsession.proto

package com.ftf.coral.admin.protobuf;

/**
 * Protobuf type {@code ftf.coral.admin.protobuf.ScAccountInfo}
 */
public  final class ScAccountInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ftf.coral.admin.protobuf.ScAccountInfo)
    ScAccountInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ScAccountInfo.newBuilder() to construct.
  private ScAccountInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ScAccountInfo() {
    username_ = "";
    roles_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ScAccountInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ScAccountInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.Int32Value.Builder subBuilder = null;
            if (category_ != null) {
              subBuilder = category_.toBuilder();
            }
            category_ = input.readMessage(com.google.protobuf.Int32Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(category_);
              category_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.google.protobuf.Int64Value.Builder subBuilder = null;
            if (accountId_ != null) {
              subBuilder = accountId_.toBuilder();
            }
            accountId_ = input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(accountId_);
              accountId_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            username_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              roles_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            roles_.add(s);
            break;
          }
          case 42: {
            com.google.protobuf.Int64Value.Builder subBuilder = null;
            if (loginTime_ != null) {
              subBuilder = loginTime_.toBuilder();
            }
            loginTime_ = input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(loginTime_);
              loginTime_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        roles_ = roles_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ftf.coral.admin.protobuf.Scsession.internal_static_ftf_coral_admin_protobuf_ScAccountInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ftf.coral.admin.protobuf.Scsession.internal_static_ftf_coral_admin_protobuf_ScAccountInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ftf.coral.admin.protobuf.ScAccountInfo.class, com.ftf.coral.admin.protobuf.ScAccountInfo.Builder.class);
  }

  public static final int CATEGORY_FIELD_NUMBER = 1;
  private com.google.protobuf.Int32Value category_;
  /**
   * <code>.google.protobuf.Int32Value category = 1;</code>
   */
  public boolean hasCategory() {
    return category_ != null;
  }
  /**
   * <code>.google.protobuf.Int32Value category = 1;</code>
   */
  public com.google.protobuf.Int32Value getCategory() {
    return category_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : category_;
  }
  /**
   * <code>.google.protobuf.Int32Value category = 1;</code>
   */
  public com.google.protobuf.Int32ValueOrBuilder getCategoryOrBuilder() {
    return getCategory();
  }

  public static final int ACCOUNTID_FIELD_NUMBER = 2;
  private com.google.protobuf.Int64Value accountId_;
  /**
   * <code>.google.protobuf.Int64Value accountId = 2;</code>
   */
  public boolean hasAccountId() {
    return accountId_ != null;
  }
  /**
   * <code>.google.protobuf.Int64Value accountId = 2;</code>
   */
  public com.google.protobuf.Int64Value getAccountId() {
    return accountId_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : accountId_;
  }
  /**
   * <code>.google.protobuf.Int64Value accountId = 2;</code>
   */
  public com.google.protobuf.Int64ValueOrBuilder getAccountIdOrBuilder() {
    return getAccountId();
  }

  public static final int USERNAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object username_;
  /**
   * <code>string username = 3;</code>
   */
  public java.lang.String getUsername() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      username_ = s;
      return s;
    }
  }
  /**
   * <code>string username = 3;</code>
   */
  public com.google.protobuf.ByteString
      getUsernameBytes() {
    java.lang.Object ref = username_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      username_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROLES_FIELD_NUMBER = 4;
  private com.google.protobuf.LazyStringList roles_;
  /**
   * <code>repeated string roles = 4;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getRolesList() {
    return roles_;
  }
  /**
   * <code>repeated string roles = 4;</code>
   */
  public int getRolesCount() {
    return roles_.size();
  }
  /**
   * <code>repeated string roles = 4;</code>
   */
  public java.lang.String getRoles(int index) {
    return roles_.get(index);
  }
  /**
   * <code>repeated string roles = 4;</code>
   */
  public com.google.protobuf.ByteString
      getRolesBytes(int index) {
    return roles_.getByteString(index);
  }

  public static final int LOGINTIME_FIELD_NUMBER = 5;
  private com.google.protobuf.Int64Value loginTime_;
  /**
   * <pre>
   * 登录时间
   * </pre>
   *
   * <code>.google.protobuf.Int64Value loginTime = 5;</code>
   */
  public boolean hasLoginTime() {
    return loginTime_ != null;
  }
  /**
   * <pre>
   * 登录时间
   * </pre>
   *
   * <code>.google.protobuf.Int64Value loginTime = 5;</code>
   */
  public com.google.protobuf.Int64Value getLoginTime() {
    return loginTime_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : loginTime_;
  }
  /**
   * <pre>
   * 登录时间
   * </pre>
   *
   * <code>.google.protobuf.Int64Value loginTime = 5;</code>
   */
  public com.google.protobuf.Int64ValueOrBuilder getLoginTimeOrBuilder() {
    return getLoginTime();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (category_ != null) {
      output.writeMessage(1, getCategory());
    }
    if (accountId_ != null) {
      output.writeMessage(2, getAccountId());
    }
    if (!getUsernameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, username_);
    }
    for (int i = 0; i < roles_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, roles_.getRaw(i));
    }
    if (loginTime_ != null) {
      output.writeMessage(5, getLoginTime());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (category_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCategory());
    }
    if (accountId_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getAccountId());
    }
    if (!getUsernameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, username_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < roles_.size(); i++) {
        dataSize += computeStringSizeNoTag(roles_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getRolesList().size();
    }
    if (loginTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getLoginTime());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ftf.coral.admin.protobuf.ScAccountInfo)) {
      return super.equals(obj);
    }
    com.ftf.coral.admin.protobuf.ScAccountInfo other = (com.ftf.coral.admin.protobuf.ScAccountInfo) obj;

    if (hasCategory() != other.hasCategory()) return false;
    if (hasCategory()) {
      if (!getCategory()
          .equals(other.getCategory())) return false;
    }
    if (hasAccountId() != other.hasAccountId()) return false;
    if (hasAccountId()) {
      if (!getAccountId()
          .equals(other.getAccountId())) return false;
    }
    if (!getUsername()
        .equals(other.getUsername())) return false;
    if (!getRolesList()
        .equals(other.getRolesList())) return false;
    if (hasLoginTime() != other.hasLoginTime()) return false;
    if (hasLoginTime()) {
      if (!getLoginTime()
          .equals(other.getLoginTime())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCategory()) {
      hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
      hash = (53 * hash) + getCategory().hashCode();
    }
    if (hasAccountId()) {
      hash = (37 * hash) + ACCOUNTID_FIELD_NUMBER;
      hash = (53 * hash) + getAccountId().hashCode();
    }
    hash = (37 * hash) + USERNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUsername().hashCode();
    if (getRolesCount() > 0) {
      hash = (37 * hash) + ROLES_FIELD_NUMBER;
      hash = (53 * hash) + getRolesList().hashCode();
    }
    if (hasLoginTime()) {
      hash = (37 * hash) + LOGINTIME_FIELD_NUMBER;
      hash = (53 * hash) + getLoginTime().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ftf.coral.admin.protobuf.ScAccountInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ftf.coral.admin.protobuf.ScAccountInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ftf.coral.admin.protobuf.ScAccountInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ftf.coral.admin.protobuf.ScAccountInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ftf.coral.admin.protobuf.ScAccountInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ftf.coral.admin.protobuf.ScAccountInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ftf.coral.admin.protobuf.ScAccountInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ftf.coral.admin.protobuf.ScAccountInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ftf.coral.admin.protobuf.ScAccountInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ftf.coral.admin.protobuf.ScAccountInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ftf.coral.admin.protobuf.ScAccountInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ftf.coral.admin.protobuf.ScAccountInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ftf.coral.admin.protobuf.ScAccountInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ftf.coral.admin.protobuf.ScAccountInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ftf.coral.admin.protobuf.ScAccountInfo)
      com.ftf.coral.admin.protobuf.ScAccountInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ftf.coral.admin.protobuf.Scsession.internal_static_ftf_coral_admin_protobuf_ScAccountInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ftf.coral.admin.protobuf.Scsession.internal_static_ftf_coral_admin_protobuf_ScAccountInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ftf.coral.admin.protobuf.ScAccountInfo.class, com.ftf.coral.admin.protobuf.ScAccountInfo.Builder.class);
    }

    // Construct using com.ftf.coral.admin.protobuf.ScAccountInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (categoryBuilder_ == null) {
        category_ = null;
      } else {
        category_ = null;
        categoryBuilder_ = null;
      }
      if (accountIdBuilder_ == null) {
        accountId_ = null;
      } else {
        accountId_ = null;
        accountIdBuilder_ = null;
      }
      username_ = "";

      roles_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      if (loginTimeBuilder_ == null) {
        loginTime_ = null;
      } else {
        loginTime_ = null;
        loginTimeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ftf.coral.admin.protobuf.Scsession.internal_static_ftf_coral_admin_protobuf_ScAccountInfo_descriptor;
    }

    @java.lang.Override
    public com.ftf.coral.admin.protobuf.ScAccountInfo getDefaultInstanceForType() {
      return com.ftf.coral.admin.protobuf.ScAccountInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.ftf.coral.admin.protobuf.ScAccountInfo build() {
      com.ftf.coral.admin.protobuf.ScAccountInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ftf.coral.admin.protobuf.ScAccountInfo buildPartial() {
      com.ftf.coral.admin.protobuf.ScAccountInfo result = new com.ftf.coral.admin.protobuf.ScAccountInfo(this);
      int from_bitField0_ = bitField0_;
      if (categoryBuilder_ == null) {
        result.category_ = category_;
      } else {
        result.category_ = categoryBuilder_.build();
      }
      if (accountIdBuilder_ == null) {
        result.accountId_ = accountId_;
      } else {
        result.accountId_ = accountIdBuilder_.build();
      }
      result.username_ = username_;
      if (((bitField0_ & 0x00000001) != 0)) {
        roles_ = roles_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.roles_ = roles_;
      if (loginTimeBuilder_ == null) {
        result.loginTime_ = loginTime_;
      } else {
        result.loginTime_ = loginTimeBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ftf.coral.admin.protobuf.ScAccountInfo) {
        return mergeFrom((com.ftf.coral.admin.protobuf.ScAccountInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ftf.coral.admin.protobuf.ScAccountInfo other) {
      if (other == com.ftf.coral.admin.protobuf.ScAccountInfo.getDefaultInstance()) return this;
      if (other.hasCategory()) {
        mergeCategory(other.getCategory());
      }
      if (other.hasAccountId()) {
        mergeAccountId(other.getAccountId());
      }
      if (!other.getUsername().isEmpty()) {
        username_ = other.username_;
        onChanged();
      }
      if (!other.roles_.isEmpty()) {
        if (roles_.isEmpty()) {
          roles_ = other.roles_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureRolesIsMutable();
          roles_.addAll(other.roles_);
        }
        onChanged();
      }
      if (other.hasLoginTime()) {
        mergeLoginTime(other.getLoginTime());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ftf.coral.admin.protobuf.ScAccountInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ftf.coral.admin.protobuf.ScAccountInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.Int32Value category_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> categoryBuilder_;
    /**
     * <code>.google.protobuf.Int32Value category = 1;</code>
     */
    public boolean hasCategory() {
      return categoryBuilder_ != null || category_ != null;
    }
    /**
     * <code>.google.protobuf.Int32Value category = 1;</code>
     */
    public com.google.protobuf.Int32Value getCategory() {
      if (categoryBuilder_ == null) {
        return category_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : category_;
      } else {
        return categoryBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int32Value category = 1;</code>
     */
    public Builder setCategory(com.google.protobuf.Int32Value value) {
      if (categoryBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        category_ = value;
        onChanged();
      } else {
        categoryBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value category = 1;</code>
     */
    public Builder setCategory(
        com.google.protobuf.Int32Value.Builder builderForValue) {
      if (categoryBuilder_ == null) {
        category_ = builderForValue.build();
        onChanged();
      } else {
        categoryBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value category = 1;</code>
     */
    public Builder mergeCategory(com.google.protobuf.Int32Value value) {
      if (categoryBuilder_ == null) {
        if (category_ != null) {
          category_ =
            com.google.protobuf.Int32Value.newBuilder(category_).mergeFrom(value).buildPartial();
        } else {
          category_ = value;
        }
        onChanged();
      } else {
        categoryBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value category = 1;</code>
     */
    public Builder clearCategory() {
      if (categoryBuilder_ == null) {
        category_ = null;
        onChanged();
      } else {
        category_ = null;
        categoryBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int32Value category = 1;</code>
     */
    public com.google.protobuf.Int32Value.Builder getCategoryBuilder() {
      
      onChanged();
      return getCategoryFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int32Value category = 1;</code>
     */
    public com.google.protobuf.Int32ValueOrBuilder getCategoryOrBuilder() {
      if (categoryBuilder_ != null) {
        return categoryBuilder_.getMessageOrBuilder();
      } else {
        return category_ == null ?
            com.google.protobuf.Int32Value.getDefaultInstance() : category_;
      }
    }
    /**
     * <code>.google.protobuf.Int32Value category = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> 
        getCategoryFieldBuilder() {
      if (categoryBuilder_ == null) {
        categoryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                getCategory(),
                getParentForChildren(),
                isClean());
        category_ = null;
      }
      return categoryBuilder_;
    }

    private com.google.protobuf.Int64Value accountId_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> accountIdBuilder_;
    /**
     * <code>.google.protobuf.Int64Value accountId = 2;</code>
     */
    public boolean hasAccountId() {
      return accountIdBuilder_ != null || accountId_ != null;
    }
    /**
     * <code>.google.protobuf.Int64Value accountId = 2;</code>
     */
    public com.google.protobuf.Int64Value getAccountId() {
      if (accountIdBuilder_ == null) {
        return accountId_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : accountId_;
      } else {
        return accountIdBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Int64Value accountId = 2;</code>
     */
    public Builder setAccountId(com.google.protobuf.Int64Value value) {
      if (accountIdBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        accountId_ = value;
        onChanged();
      } else {
        accountIdBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value accountId = 2;</code>
     */
    public Builder setAccountId(
        com.google.protobuf.Int64Value.Builder builderForValue) {
      if (accountIdBuilder_ == null) {
        accountId_ = builderForValue.build();
        onChanged();
      } else {
        accountIdBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value accountId = 2;</code>
     */
    public Builder mergeAccountId(com.google.protobuf.Int64Value value) {
      if (accountIdBuilder_ == null) {
        if (accountId_ != null) {
          accountId_ =
            com.google.protobuf.Int64Value.newBuilder(accountId_).mergeFrom(value).buildPartial();
        } else {
          accountId_ = value;
        }
        onChanged();
      } else {
        accountIdBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value accountId = 2;</code>
     */
    public Builder clearAccountId() {
      if (accountIdBuilder_ == null) {
        accountId_ = null;
        onChanged();
      } else {
        accountId_ = null;
        accountIdBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Int64Value accountId = 2;</code>
     */
    public com.google.protobuf.Int64Value.Builder getAccountIdBuilder() {
      
      onChanged();
      return getAccountIdFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Int64Value accountId = 2;</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getAccountIdOrBuilder() {
      if (accountIdBuilder_ != null) {
        return accountIdBuilder_.getMessageOrBuilder();
      } else {
        return accountId_ == null ?
            com.google.protobuf.Int64Value.getDefaultInstance() : accountId_;
      }
    }
    /**
     * <code>.google.protobuf.Int64Value accountId = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> 
        getAccountIdFieldBuilder() {
      if (accountIdBuilder_ == null) {
        accountIdBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                getAccountId(),
                getParentForChildren(),
                isClean());
        accountId_ = null;
      }
      return accountIdBuilder_;
    }

    private java.lang.Object username_ = "";
    /**
     * <code>string username = 3;</code>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string username = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string username = 3;</code>
     */
    public Builder setUsername(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      username_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string username = 3;</code>
     */
    public Builder clearUsername() {
      
      username_ = getDefaultInstance().getUsername();
      onChanged();
      return this;
    }
    /**
     * <code>string username = 3;</code>
     */
    public Builder setUsernameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      username_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList roles_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureRolesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        roles_ = new com.google.protobuf.LazyStringArrayList(roles_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string roles = 4;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getRolesList() {
      return roles_.getUnmodifiableView();
    }
    /**
     * <code>repeated string roles = 4;</code>
     */
    public int getRolesCount() {
      return roles_.size();
    }
    /**
     * <code>repeated string roles = 4;</code>
     */
    public java.lang.String getRoles(int index) {
      return roles_.get(index);
    }
    /**
     * <code>repeated string roles = 4;</code>
     */
    public com.google.protobuf.ByteString
        getRolesBytes(int index) {
      return roles_.getByteString(index);
    }
    /**
     * <code>repeated string roles = 4;</code>
     */
    public Builder setRoles(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureRolesIsMutable();
      roles_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string roles = 4;</code>
     */
    public Builder addRoles(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureRolesIsMutable();
      roles_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string roles = 4;</code>
     */
    public Builder addAllRoles(
        java.lang.Iterable<java.lang.String> values) {
      ensureRolesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, roles_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string roles = 4;</code>
     */
    public Builder clearRoles() {
      roles_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string roles = 4;</code>
     */
    public Builder addRolesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureRolesIsMutable();
      roles_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.Int64Value loginTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> loginTimeBuilder_;
    /**
     * <pre>
     * 登录时间
     * </pre>
     *
     * <code>.google.protobuf.Int64Value loginTime = 5;</code>
     */
    public boolean hasLoginTime() {
      return loginTimeBuilder_ != null || loginTime_ != null;
    }
    /**
     * <pre>
     * 登录时间
     * </pre>
     *
     * <code>.google.protobuf.Int64Value loginTime = 5;</code>
     */
    public com.google.protobuf.Int64Value getLoginTime() {
      if (loginTimeBuilder_ == null) {
        return loginTime_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : loginTime_;
      } else {
        return loginTimeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 登录时间
     * </pre>
     *
     * <code>.google.protobuf.Int64Value loginTime = 5;</code>
     */
    public Builder setLoginTime(com.google.protobuf.Int64Value value) {
      if (loginTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        loginTime_ = value;
        onChanged();
      } else {
        loginTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 登录时间
     * </pre>
     *
     * <code>.google.protobuf.Int64Value loginTime = 5;</code>
     */
    public Builder setLoginTime(
        com.google.protobuf.Int64Value.Builder builderForValue) {
      if (loginTimeBuilder_ == null) {
        loginTime_ = builderForValue.build();
        onChanged();
      } else {
        loginTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 登录时间
     * </pre>
     *
     * <code>.google.protobuf.Int64Value loginTime = 5;</code>
     */
    public Builder mergeLoginTime(com.google.protobuf.Int64Value value) {
      if (loginTimeBuilder_ == null) {
        if (loginTime_ != null) {
          loginTime_ =
            com.google.protobuf.Int64Value.newBuilder(loginTime_).mergeFrom(value).buildPartial();
        } else {
          loginTime_ = value;
        }
        onChanged();
      } else {
        loginTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 登录时间
     * </pre>
     *
     * <code>.google.protobuf.Int64Value loginTime = 5;</code>
     */
    public Builder clearLoginTime() {
      if (loginTimeBuilder_ == null) {
        loginTime_ = null;
        onChanged();
      } else {
        loginTime_ = null;
        loginTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 登录时间
     * </pre>
     *
     * <code>.google.protobuf.Int64Value loginTime = 5;</code>
     */
    public com.google.protobuf.Int64Value.Builder getLoginTimeBuilder() {
      
      onChanged();
      return getLoginTimeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 登录时间
     * </pre>
     *
     * <code>.google.protobuf.Int64Value loginTime = 5;</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getLoginTimeOrBuilder() {
      if (loginTimeBuilder_ != null) {
        return loginTimeBuilder_.getMessageOrBuilder();
      } else {
        return loginTime_ == null ?
            com.google.protobuf.Int64Value.getDefaultInstance() : loginTime_;
      }
    }
    /**
     * <pre>
     * 登录时间
     * </pre>
     *
     * <code>.google.protobuf.Int64Value loginTime = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> 
        getLoginTimeFieldBuilder() {
      if (loginTimeBuilder_ == null) {
        loginTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                getLoginTime(),
                getParentForChildren(),
                isClean());
        loginTime_ = null;
      }
      return loginTimeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ftf.coral.admin.protobuf.ScAccountInfo)
  }

  // @@protoc_insertion_point(class_scope:ftf.coral.admin.protobuf.ScAccountInfo)
  private static final com.ftf.coral.admin.protobuf.ScAccountInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ftf.coral.admin.protobuf.ScAccountInfo();
  }

  public static com.ftf.coral.admin.protobuf.ScAccountInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ScAccountInfo>
      PARSER = new com.google.protobuf.AbstractParser<ScAccountInfo>() {
    @java.lang.Override
    public ScAccountInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ScAccountInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ScAccountInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ScAccountInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ftf.coral.admin.protobuf.ScAccountInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

