// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scsession.proto

package com.ftf.coral.admin.protobuf;

public final class Scsession {
  private Scsession() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ftf_coral_admin_protobuf_ScSessionInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ftf_coral_admin_protobuf_ScSessionInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ftf_coral_admin_protobuf_ScAccountInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ftf_coral_admin_protobuf_ScAccountInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ftf_coral_admin_protobuf_ScTokenSessionInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ftf_coral_admin_protobuf_ScTokenSessionInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017scsession.proto\022\030ftf.coral.admin.proto" +
      "buf\032\016wrappers.proto\"S\n\rScSessionInfo\022.\n\t" +
      "beginTime\030\001 \001(\0132\033.google.protobuf.Int64V" +
      "alue\022\022\n\ndeviceInfo\030\002 \001(\t\"\277\001\n\rScAccountIn" +
      "fo\022-\n\010category\030\001 \001(\0132\033.google.protobuf.I" +
      "nt32Value\022.\n\taccountId\030\002 \001(\0132\033.google.pr" +
      "otobuf.Int64Value\022\020\n\010username\030\003 \001(\t\022\r\n\005r" +
      "oles\030\004 \003(\t\022.\n\tloginTime\030\005 \001(\0132\033.google.p" +
      "rotobuf.Int64Value\"\224\001\n\022ScTokenSessionInf" +
      "o\022>\n\rscSessionInfo\030\001 \001(\0132\'.ftf.coral.adm" +
      "in.protobuf.ScSessionInfo\022>\n\rscAccountIn" +
      "fo\030\002 \001(\0132\'.ftf.coral.admin.protobuf.ScAc" +
      "countInfoB \n\034com.ftf.coral.admin.protobu" +
      "fP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_ftf_coral_admin_protobuf_ScSessionInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ftf_coral_admin_protobuf_ScSessionInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ftf_coral_admin_protobuf_ScSessionInfo_descriptor,
        new java.lang.String[] { "BeginTime", "DeviceInfo", });
    internal_static_ftf_coral_admin_protobuf_ScAccountInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ftf_coral_admin_protobuf_ScAccountInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ftf_coral_admin_protobuf_ScAccountInfo_descriptor,
        new java.lang.String[] { "Category", "AccountId", "Username", "Roles", "LoginTime", });
    internal_static_ftf_coral_admin_protobuf_ScTokenSessionInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ftf_coral_admin_protobuf_ScTokenSessionInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ftf_coral_admin_protobuf_ScTokenSessionInfo_descriptor,
        new java.lang.String[] { "ScSessionInfo", "ScAccountInfo", });
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
