// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scsession.proto

package com.ftf.coral.admin.protobuf;

public interface ScSessionInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ftf.coral.admin.protobuf.ScSessionInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 开始时间
   * </pre>
   *
   * <code>.google.protobuf.Int64Value beginTime = 1;</code>
   */
  boolean hasBeginTime();
  /**
   * <pre>
   * 开始时间
   * </pre>
   *
   * <code>.google.protobuf.Int64Value beginTime = 1;</code>
   */
  com.google.protobuf.Int64Value getBeginTime();
  /**
   * <pre>
   * 开始时间
   * </pre>
   *
   * <code>.google.protobuf.Int64Value beginTime = 1;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getBeginTimeOrBuilder();

  /**
   * <pre>
   * 设备信息
   * </pre>
   *
   * <code>string deviceInfo = 2;</code>
   */
  java.lang.String getDeviceInfo();
  /**
   * <pre>
   * 设备信息
   * </pre>
   *
   * <code>string deviceInfo = 2;</code>
   */
  com.google.protobuf.ByteString
      getDeviceInfoBytes();
}
