// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scsession.proto

package com.ftf.coral.admin.protobuf;

/**
 * Protobuf type {@code ftf.coral.admin.protobuf.ScSessionInfo}
 */
public  final class ScSessionInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ftf.coral.admin.protobuf.ScSessionInfo)
    ScSessionInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ScSessionInfo.newBuilder() to construct.
  private ScSessionInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ScSessionInfo() {
    deviceInfo_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ScSessionInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ScSessionInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.Int64Value.Builder subBuilder = null;
            if (beginTime_ != null) {
              subBuilder = beginTime_.toBuilder();
            }
            beginTime_ = input.readMessage(com.google.protobuf.Int64Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(beginTime_);
              beginTime_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            deviceInfo_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ftf.coral.admin.protobuf.Scsession.internal_static_ftf_coral_admin_protobuf_ScSessionInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ftf.coral.admin.protobuf.Scsession.internal_static_ftf_coral_admin_protobuf_ScSessionInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ftf.coral.admin.protobuf.ScSessionInfo.class, com.ftf.coral.admin.protobuf.ScSessionInfo.Builder.class);
  }

  public static final int BEGINTIME_FIELD_NUMBER = 1;
  private com.google.protobuf.Int64Value beginTime_;
  /**
   * <pre>
   * 开始时间
   * </pre>
   *
   * <code>.google.protobuf.Int64Value beginTime = 1;</code>
   */
  public boolean hasBeginTime() {
    return beginTime_ != null;
  }
  /**
   * <pre>
   * 开始时间
   * </pre>
   *
   * <code>.google.protobuf.Int64Value beginTime = 1;</code>
   */
  public com.google.protobuf.Int64Value getBeginTime() {
    return beginTime_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : beginTime_;
  }
  /**
   * <pre>
   * 开始时间
   * </pre>
   *
   * <code>.google.protobuf.Int64Value beginTime = 1;</code>
   */
  public com.google.protobuf.Int64ValueOrBuilder getBeginTimeOrBuilder() {
    return getBeginTime();
  }

  public static final int DEVICEINFO_FIELD_NUMBER = 2;
  private volatile java.lang.Object deviceInfo_;
  /**
   * <pre>
   * 设备信息
   * </pre>
   *
   * <code>string deviceInfo = 2;</code>
   */
  public java.lang.String getDeviceInfo() {
    java.lang.Object ref = deviceInfo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceInfo_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 设备信息
   * </pre>
   *
   * <code>string deviceInfo = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDeviceInfoBytes() {
    java.lang.Object ref = deviceInfo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceInfo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (beginTime_ != null) {
      output.writeMessage(1, getBeginTime());
    }
    if (!getDeviceInfoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, deviceInfo_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (beginTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBeginTime());
    }
    if (!getDeviceInfoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, deviceInfo_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ftf.coral.admin.protobuf.ScSessionInfo)) {
      return super.equals(obj);
    }
    com.ftf.coral.admin.protobuf.ScSessionInfo other = (com.ftf.coral.admin.protobuf.ScSessionInfo) obj;

    if (hasBeginTime() != other.hasBeginTime()) return false;
    if (hasBeginTime()) {
      if (!getBeginTime()
          .equals(other.getBeginTime())) return false;
    }
    if (!getDeviceInfo()
        .equals(other.getDeviceInfo())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBeginTime()) {
      hash = (37 * hash) + BEGINTIME_FIELD_NUMBER;
      hash = (53 * hash) + getBeginTime().hashCode();
    }
    hash = (37 * hash) + DEVICEINFO_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceInfo().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ftf.coral.admin.protobuf.ScSessionInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ftf.coral.admin.protobuf.ScSessionInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ftf.coral.admin.protobuf.ScSessionInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ftf.coral.admin.protobuf.ScSessionInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ftf.coral.admin.protobuf.ScSessionInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ftf.coral.admin.protobuf.ScSessionInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ftf.coral.admin.protobuf.ScSessionInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ftf.coral.admin.protobuf.ScSessionInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ftf.coral.admin.protobuf.ScSessionInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ftf.coral.admin.protobuf.ScSessionInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ftf.coral.admin.protobuf.ScSessionInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ftf.coral.admin.protobuf.ScSessionInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ftf.coral.admin.protobuf.ScSessionInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ftf.coral.admin.protobuf.ScSessionInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ftf.coral.admin.protobuf.ScSessionInfo)
      com.ftf.coral.admin.protobuf.ScSessionInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ftf.coral.admin.protobuf.Scsession.internal_static_ftf_coral_admin_protobuf_ScSessionInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ftf.coral.admin.protobuf.Scsession.internal_static_ftf_coral_admin_protobuf_ScSessionInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ftf.coral.admin.protobuf.ScSessionInfo.class, com.ftf.coral.admin.protobuf.ScSessionInfo.Builder.class);
    }

    // Construct using com.ftf.coral.admin.protobuf.ScSessionInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (beginTimeBuilder_ == null) {
        beginTime_ = null;
      } else {
        beginTime_ = null;
        beginTimeBuilder_ = null;
      }
      deviceInfo_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ftf.coral.admin.protobuf.Scsession.internal_static_ftf_coral_admin_protobuf_ScSessionInfo_descriptor;
    }

    @java.lang.Override
    public com.ftf.coral.admin.protobuf.ScSessionInfo getDefaultInstanceForType() {
      return com.ftf.coral.admin.protobuf.ScSessionInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.ftf.coral.admin.protobuf.ScSessionInfo build() {
      com.ftf.coral.admin.protobuf.ScSessionInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ftf.coral.admin.protobuf.ScSessionInfo buildPartial() {
      com.ftf.coral.admin.protobuf.ScSessionInfo result = new com.ftf.coral.admin.protobuf.ScSessionInfo(this);
      if (beginTimeBuilder_ == null) {
        result.beginTime_ = beginTime_;
      } else {
        result.beginTime_ = beginTimeBuilder_.build();
      }
      result.deviceInfo_ = deviceInfo_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ftf.coral.admin.protobuf.ScSessionInfo) {
        return mergeFrom((com.ftf.coral.admin.protobuf.ScSessionInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ftf.coral.admin.protobuf.ScSessionInfo other) {
      if (other == com.ftf.coral.admin.protobuf.ScSessionInfo.getDefaultInstance()) return this;
      if (other.hasBeginTime()) {
        mergeBeginTime(other.getBeginTime());
      }
      if (!other.getDeviceInfo().isEmpty()) {
        deviceInfo_ = other.deviceInfo_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ftf.coral.admin.protobuf.ScSessionInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ftf.coral.admin.protobuf.ScSessionInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.google.protobuf.Int64Value beginTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> beginTimeBuilder_;
    /**
     * <pre>
     * 开始时间
     * </pre>
     *
     * <code>.google.protobuf.Int64Value beginTime = 1;</code>
     */
    public boolean hasBeginTime() {
      return beginTimeBuilder_ != null || beginTime_ != null;
    }
    /**
     * <pre>
     * 开始时间
     * </pre>
     *
     * <code>.google.protobuf.Int64Value beginTime = 1;</code>
     */
    public com.google.protobuf.Int64Value getBeginTime() {
      if (beginTimeBuilder_ == null) {
        return beginTime_ == null ? com.google.protobuf.Int64Value.getDefaultInstance() : beginTime_;
      } else {
        return beginTimeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * 开始时间
     * </pre>
     *
     * <code>.google.protobuf.Int64Value beginTime = 1;</code>
     */
    public Builder setBeginTime(com.google.protobuf.Int64Value value) {
      if (beginTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        beginTime_ = value;
        onChanged();
      } else {
        beginTimeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * 开始时间
     * </pre>
     *
     * <code>.google.protobuf.Int64Value beginTime = 1;</code>
     */
    public Builder setBeginTime(
        com.google.protobuf.Int64Value.Builder builderForValue) {
      if (beginTimeBuilder_ == null) {
        beginTime_ = builderForValue.build();
        onChanged();
      } else {
        beginTimeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * 开始时间
     * </pre>
     *
     * <code>.google.protobuf.Int64Value beginTime = 1;</code>
     */
    public Builder mergeBeginTime(com.google.protobuf.Int64Value value) {
      if (beginTimeBuilder_ == null) {
        if (beginTime_ != null) {
          beginTime_ =
            com.google.protobuf.Int64Value.newBuilder(beginTime_).mergeFrom(value).buildPartial();
        } else {
          beginTime_ = value;
        }
        onChanged();
      } else {
        beginTimeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * 开始时间
     * </pre>
     *
     * <code>.google.protobuf.Int64Value beginTime = 1;</code>
     */
    public Builder clearBeginTime() {
      if (beginTimeBuilder_ == null) {
        beginTime_ = null;
        onChanged();
      } else {
        beginTime_ = null;
        beginTimeBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * 开始时间
     * </pre>
     *
     * <code>.google.protobuf.Int64Value beginTime = 1;</code>
     */
    public com.google.protobuf.Int64Value.Builder getBeginTimeBuilder() {
      
      onChanged();
      return getBeginTimeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * 开始时间
     * </pre>
     *
     * <code>.google.protobuf.Int64Value beginTime = 1;</code>
     */
    public com.google.protobuf.Int64ValueOrBuilder getBeginTimeOrBuilder() {
      if (beginTimeBuilder_ != null) {
        return beginTimeBuilder_.getMessageOrBuilder();
      } else {
        return beginTime_ == null ?
            com.google.protobuf.Int64Value.getDefaultInstance() : beginTime_;
      }
    }
    /**
     * <pre>
     * 开始时间
     * </pre>
     *
     * <code>.google.protobuf.Int64Value beginTime = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder> 
        getBeginTimeFieldBuilder() {
      if (beginTimeBuilder_ == null) {
        beginTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int64Value, com.google.protobuf.Int64Value.Builder, com.google.protobuf.Int64ValueOrBuilder>(
                getBeginTime(),
                getParentForChildren(),
                isClean());
        beginTime_ = null;
      }
      return beginTimeBuilder_;
    }

    private java.lang.Object deviceInfo_ = "";
    /**
     * <pre>
     * 设备信息
     * </pre>
     *
     * <code>string deviceInfo = 2;</code>
     */
    public java.lang.String getDeviceInfo() {
      java.lang.Object ref = deviceInfo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceInfo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 设备信息
     * </pre>
     *
     * <code>string deviceInfo = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceInfoBytes() {
      java.lang.Object ref = deviceInfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 设备信息
     * </pre>
     *
     * <code>string deviceInfo = 2;</code>
     */
    public Builder setDeviceInfo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceInfo_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 设备信息
     * </pre>
     *
     * <code>string deviceInfo = 2;</code>
     */
    public Builder clearDeviceInfo() {
      
      deviceInfo_ = getDefaultInstance().getDeviceInfo();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 设备信息
     * </pre>
     *
     * <code>string deviceInfo = 2;</code>
     */
    public Builder setDeviceInfoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceInfo_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ftf.coral.admin.protobuf.ScSessionInfo)
  }

  // @@protoc_insertion_point(class_scope:ftf.coral.admin.protobuf.ScSessionInfo)
  private static final com.ftf.coral.admin.protobuf.ScSessionInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ftf.coral.admin.protobuf.ScSessionInfo();
  }

  public static com.ftf.coral.admin.protobuf.ScSessionInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ScSessionInfo>
      PARSER = new com.google.protobuf.AbstractParser<ScSessionInfo>() {
    @java.lang.Override
    public ScSessionInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ScSessionInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ScSessionInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ScSessionInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ftf.coral.admin.protobuf.ScSessionInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

