// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scsession.proto

package com.ftf.coral.admin.protobuf;

/**
 * Protobuf type {@code ftf.coral.admin.protobuf.ScTokenSessionInfo}
 */
public  final class ScTokenSessionInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ftf.coral.admin.protobuf.ScTokenSessionInfo)
    ScTokenSessionInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ScTokenSessionInfo.newBuilder() to construct.
  private ScTokenSessionInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ScTokenSessionInfo() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ScTokenSessionInfo();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ScTokenSessionInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.ftf.coral.admin.protobuf.ScSessionInfo.Builder subBuilder = null;
            if (scSessionInfo_ != null) {
              subBuilder = scSessionInfo_.toBuilder();
            }
            scSessionInfo_ = input.readMessage(com.ftf.coral.admin.protobuf.ScSessionInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(scSessionInfo_);
              scSessionInfo_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.ftf.coral.admin.protobuf.ScAccountInfo.Builder subBuilder = null;
            if (scAccountInfo_ != null) {
              subBuilder = scAccountInfo_.toBuilder();
            }
            scAccountInfo_ = input.readMessage(com.ftf.coral.admin.protobuf.ScAccountInfo.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(scAccountInfo_);
              scAccountInfo_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.ftf.coral.admin.protobuf.Scsession.internal_static_ftf_coral_admin_protobuf_ScTokenSessionInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.ftf.coral.admin.protobuf.Scsession.internal_static_ftf_coral_admin_protobuf_ScTokenSessionInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.ftf.coral.admin.protobuf.ScTokenSessionInfo.class, com.ftf.coral.admin.protobuf.ScTokenSessionInfo.Builder.class);
  }

  public static final int SCSESSIONINFO_FIELD_NUMBER = 1;
  private com.ftf.coral.admin.protobuf.ScSessionInfo scSessionInfo_;
  /**
   * <code>.ftf.coral.admin.protobuf.ScSessionInfo scSessionInfo = 1;</code>
   */
  public boolean hasScSessionInfo() {
    return scSessionInfo_ != null;
  }
  /**
   * <code>.ftf.coral.admin.protobuf.ScSessionInfo scSessionInfo = 1;</code>
   */
  public com.ftf.coral.admin.protobuf.ScSessionInfo getScSessionInfo() {
    return scSessionInfo_ == null ? com.ftf.coral.admin.protobuf.ScSessionInfo.getDefaultInstance() : scSessionInfo_;
  }
  /**
   * <code>.ftf.coral.admin.protobuf.ScSessionInfo scSessionInfo = 1;</code>
   */
  public com.ftf.coral.admin.protobuf.ScSessionInfoOrBuilder getScSessionInfoOrBuilder() {
    return getScSessionInfo();
  }

  public static final int SCACCOUNTINFO_FIELD_NUMBER = 2;
  private com.ftf.coral.admin.protobuf.ScAccountInfo scAccountInfo_;
  /**
   * <code>.ftf.coral.admin.protobuf.ScAccountInfo scAccountInfo = 2;</code>
   */
  public boolean hasScAccountInfo() {
    return scAccountInfo_ != null;
  }
  /**
   * <code>.ftf.coral.admin.protobuf.ScAccountInfo scAccountInfo = 2;</code>
   */
  public com.ftf.coral.admin.protobuf.ScAccountInfo getScAccountInfo() {
    return scAccountInfo_ == null ? com.ftf.coral.admin.protobuf.ScAccountInfo.getDefaultInstance() : scAccountInfo_;
  }
  /**
   * <code>.ftf.coral.admin.protobuf.ScAccountInfo scAccountInfo = 2;</code>
   */
  public com.ftf.coral.admin.protobuf.ScAccountInfoOrBuilder getScAccountInfoOrBuilder() {
    return getScAccountInfo();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (scSessionInfo_ != null) {
      output.writeMessage(1, getScSessionInfo());
    }
    if (scAccountInfo_ != null) {
      output.writeMessage(2, getScAccountInfo());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (scSessionInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getScSessionInfo());
    }
    if (scAccountInfo_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getScAccountInfo());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.ftf.coral.admin.protobuf.ScTokenSessionInfo)) {
      return super.equals(obj);
    }
    com.ftf.coral.admin.protobuf.ScTokenSessionInfo other = (com.ftf.coral.admin.protobuf.ScTokenSessionInfo) obj;

    if (hasScSessionInfo() != other.hasScSessionInfo()) return false;
    if (hasScSessionInfo()) {
      if (!getScSessionInfo()
          .equals(other.getScSessionInfo())) return false;
    }
    if (hasScAccountInfo() != other.hasScAccountInfo()) return false;
    if (hasScAccountInfo()) {
      if (!getScAccountInfo()
          .equals(other.getScAccountInfo())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasScSessionInfo()) {
      hash = (37 * hash) + SCSESSIONINFO_FIELD_NUMBER;
      hash = (53 * hash) + getScSessionInfo().hashCode();
    }
    if (hasScAccountInfo()) {
      hash = (37 * hash) + SCACCOUNTINFO_FIELD_NUMBER;
      hash = (53 * hash) + getScAccountInfo().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.ftf.coral.admin.protobuf.ScTokenSessionInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ftf.coral.admin.protobuf.ScTokenSessionInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ftf.coral.admin.protobuf.ScTokenSessionInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ftf.coral.admin.protobuf.ScTokenSessionInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ftf.coral.admin.protobuf.ScTokenSessionInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.ftf.coral.admin.protobuf.ScTokenSessionInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.ftf.coral.admin.protobuf.ScTokenSessionInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ftf.coral.admin.protobuf.ScTokenSessionInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ftf.coral.admin.protobuf.ScTokenSessionInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.ftf.coral.admin.protobuf.ScTokenSessionInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.ftf.coral.admin.protobuf.ScTokenSessionInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.ftf.coral.admin.protobuf.ScTokenSessionInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.ftf.coral.admin.protobuf.ScTokenSessionInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ftf.coral.admin.protobuf.ScTokenSessionInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ftf.coral.admin.protobuf.ScTokenSessionInfo)
      com.ftf.coral.admin.protobuf.ScTokenSessionInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.ftf.coral.admin.protobuf.Scsession.internal_static_ftf_coral_admin_protobuf_ScTokenSessionInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.ftf.coral.admin.protobuf.Scsession.internal_static_ftf_coral_admin_protobuf_ScTokenSessionInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.ftf.coral.admin.protobuf.ScTokenSessionInfo.class, com.ftf.coral.admin.protobuf.ScTokenSessionInfo.Builder.class);
    }

    // Construct using com.ftf.coral.admin.protobuf.ScTokenSessionInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (scSessionInfoBuilder_ == null) {
        scSessionInfo_ = null;
      } else {
        scSessionInfo_ = null;
        scSessionInfoBuilder_ = null;
      }
      if (scAccountInfoBuilder_ == null) {
        scAccountInfo_ = null;
      } else {
        scAccountInfo_ = null;
        scAccountInfoBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.ftf.coral.admin.protobuf.Scsession.internal_static_ftf_coral_admin_protobuf_ScTokenSessionInfo_descriptor;
    }

    @java.lang.Override
    public com.ftf.coral.admin.protobuf.ScTokenSessionInfo getDefaultInstanceForType() {
      return com.ftf.coral.admin.protobuf.ScTokenSessionInfo.getDefaultInstance();
    }

    @java.lang.Override
    public com.ftf.coral.admin.protobuf.ScTokenSessionInfo build() {
      com.ftf.coral.admin.protobuf.ScTokenSessionInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.ftf.coral.admin.protobuf.ScTokenSessionInfo buildPartial() {
      com.ftf.coral.admin.protobuf.ScTokenSessionInfo result = new com.ftf.coral.admin.protobuf.ScTokenSessionInfo(this);
      if (scSessionInfoBuilder_ == null) {
        result.scSessionInfo_ = scSessionInfo_;
      } else {
        result.scSessionInfo_ = scSessionInfoBuilder_.build();
      }
      if (scAccountInfoBuilder_ == null) {
        result.scAccountInfo_ = scAccountInfo_;
      } else {
        result.scAccountInfo_ = scAccountInfoBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.ftf.coral.admin.protobuf.ScTokenSessionInfo) {
        return mergeFrom((com.ftf.coral.admin.protobuf.ScTokenSessionInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.ftf.coral.admin.protobuf.ScTokenSessionInfo other) {
      if (other == com.ftf.coral.admin.protobuf.ScTokenSessionInfo.getDefaultInstance()) return this;
      if (other.hasScSessionInfo()) {
        mergeScSessionInfo(other.getScSessionInfo());
      }
      if (other.hasScAccountInfo()) {
        mergeScAccountInfo(other.getScAccountInfo());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.ftf.coral.admin.protobuf.ScTokenSessionInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.ftf.coral.admin.protobuf.ScTokenSessionInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.ftf.coral.admin.protobuf.ScSessionInfo scSessionInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ftf.coral.admin.protobuf.ScSessionInfo, com.ftf.coral.admin.protobuf.ScSessionInfo.Builder, com.ftf.coral.admin.protobuf.ScSessionInfoOrBuilder> scSessionInfoBuilder_;
    /**
     * <code>.ftf.coral.admin.protobuf.ScSessionInfo scSessionInfo = 1;</code>
     */
    public boolean hasScSessionInfo() {
      return scSessionInfoBuilder_ != null || scSessionInfo_ != null;
    }
    /**
     * <code>.ftf.coral.admin.protobuf.ScSessionInfo scSessionInfo = 1;</code>
     */
    public com.ftf.coral.admin.protobuf.ScSessionInfo getScSessionInfo() {
      if (scSessionInfoBuilder_ == null) {
        return scSessionInfo_ == null ? com.ftf.coral.admin.protobuf.ScSessionInfo.getDefaultInstance() : scSessionInfo_;
      } else {
        return scSessionInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.ftf.coral.admin.protobuf.ScSessionInfo scSessionInfo = 1;</code>
     */
    public Builder setScSessionInfo(com.ftf.coral.admin.protobuf.ScSessionInfo value) {
      if (scSessionInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        scSessionInfo_ = value;
        onChanged();
      } else {
        scSessionInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ftf.coral.admin.protobuf.ScSessionInfo scSessionInfo = 1;</code>
     */
    public Builder setScSessionInfo(
        com.ftf.coral.admin.protobuf.ScSessionInfo.Builder builderForValue) {
      if (scSessionInfoBuilder_ == null) {
        scSessionInfo_ = builderForValue.build();
        onChanged();
      } else {
        scSessionInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ftf.coral.admin.protobuf.ScSessionInfo scSessionInfo = 1;</code>
     */
    public Builder mergeScSessionInfo(com.ftf.coral.admin.protobuf.ScSessionInfo value) {
      if (scSessionInfoBuilder_ == null) {
        if (scSessionInfo_ != null) {
          scSessionInfo_ =
            com.ftf.coral.admin.protobuf.ScSessionInfo.newBuilder(scSessionInfo_).mergeFrom(value).buildPartial();
        } else {
          scSessionInfo_ = value;
        }
        onChanged();
      } else {
        scSessionInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ftf.coral.admin.protobuf.ScSessionInfo scSessionInfo = 1;</code>
     */
    public Builder clearScSessionInfo() {
      if (scSessionInfoBuilder_ == null) {
        scSessionInfo_ = null;
        onChanged();
      } else {
        scSessionInfo_ = null;
        scSessionInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ftf.coral.admin.protobuf.ScSessionInfo scSessionInfo = 1;</code>
     */
    public com.ftf.coral.admin.protobuf.ScSessionInfo.Builder getScSessionInfoBuilder() {
      
      onChanged();
      return getScSessionInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.ftf.coral.admin.protobuf.ScSessionInfo scSessionInfo = 1;</code>
     */
    public com.ftf.coral.admin.protobuf.ScSessionInfoOrBuilder getScSessionInfoOrBuilder() {
      if (scSessionInfoBuilder_ != null) {
        return scSessionInfoBuilder_.getMessageOrBuilder();
      } else {
        return scSessionInfo_ == null ?
            com.ftf.coral.admin.protobuf.ScSessionInfo.getDefaultInstance() : scSessionInfo_;
      }
    }
    /**
     * <code>.ftf.coral.admin.protobuf.ScSessionInfo scSessionInfo = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ftf.coral.admin.protobuf.ScSessionInfo, com.ftf.coral.admin.protobuf.ScSessionInfo.Builder, com.ftf.coral.admin.protobuf.ScSessionInfoOrBuilder> 
        getScSessionInfoFieldBuilder() {
      if (scSessionInfoBuilder_ == null) {
        scSessionInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ftf.coral.admin.protobuf.ScSessionInfo, com.ftf.coral.admin.protobuf.ScSessionInfo.Builder, com.ftf.coral.admin.protobuf.ScSessionInfoOrBuilder>(
                getScSessionInfo(),
                getParentForChildren(),
                isClean());
        scSessionInfo_ = null;
      }
      return scSessionInfoBuilder_;
    }

    private com.ftf.coral.admin.protobuf.ScAccountInfo scAccountInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ftf.coral.admin.protobuf.ScAccountInfo, com.ftf.coral.admin.protobuf.ScAccountInfo.Builder, com.ftf.coral.admin.protobuf.ScAccountInfoOrBuilder> scAccountInfoBuilder_;
    /**
     * <code>.ftf.coral.admin.protobuf.ScAccountInfo scAccountInfo = 2;</code>
     */
    public boolean hasScAccountInfo() {
      return scAccountInfoBuilder_ != null || scAccountInfo_ != null;
    }
    /**
     * <code>.ftf.coral.admin.protobuf.ScAccountInfo scAccountInfo = 2;</code>
     */
    public com.ftf.coral.admin.protobuf.ScAccountInfo getScAccountInfo() {
      if (scAccountInfoBuilder_ == null) {
        return scAccountInfo_ == null ? com.ftf.coral.admin.protobuf.ScAccountInfo.getDefaultInstance() : scAccountInfo_;
      } else {
        return scAccountInfoBuilder_.getMessage();
      }
    }
    /**
     * <code>.ftf.coral.admin.protobuf.ScAccountInfo scAccountInfo = 2;</code>
     */
    public Builder setScAccountInfo(com.ftf.coral.admin.protobuf.ScAccountInfo value) {
      if (scAccountInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        scAccountInfo_ = value;
        onChanged();
      } else {
        scAccountInfoBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.ftf.coral.admin.protobuf.ScAccountInfo scAccountInfo = 2;</code>
     */
    public Builder setScAccountInfo(
        com.ftf.coral.admin.protobuf.ScAccountInfo.Builder builderForValue) {
      if (scAccountInfoBuilder_ == null) {
        scAccountInfo_ = builderForValue.build();
        onChanged();
      } else {
        scAccountInfoBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.ftf.coral.admin.protobuf.ScAccountInfo scAccountInfo = 2;</code>
     */
    public Builder mergeScAccountInfo(com.ftf.coral.admin.protobuf.ScAccountInfo value) {
      if (scAccountInfoBuilder_ == null) {
        if (scAccountInfo_ != null) {
          scAccountInfo_ =
            com.ftf.coral.admin.protobuf.ScAccountInfo.newBuilder(scAccountInfo_).mergeFrom(value).buildPartial();
        } else {
          scAccountInfo_ = value;
        }
        onChanged();
      } else {
        scAccountInfoBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.ftf.coral.admin.protobuf.ScAccountInfo scAccountInfo = 2;</code>
     */
    public Builder clearScAccountInfo() {
      if (scAccountInfoBuilder_ == null) {
        scAccountInfo_ = null;
        onChanged();
      } else {
        scAccountInfo_ = null;
        scAccountInfoBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.ftf.coral.admin.protobuf.ScAccountInfo scAccountInfo = 2;</code>
     */
    public com.ftf.coral.admin.protobuf.ScAccountInfo.Builder getScAccountInfoBuilder() {
      
      onChanged();
      return getScAccountInfoFieldBuilder().getBuilder();
    }
    /**
     * <code>.ftf.coral.admin.protobuf.ScAccountInfo scAccountInfo = 2;</code>
     */
    public com.ftf.coral.admin.protobuf.ScAccountInfoOrBuilder getScAccountInfoOrBuilder() {
      if (scAccountInfoBuilder_ != null) {
        return scAccountInfoBuilder_.getMessageOrBuilder();
      } else {
        return scAccountInfo_ == null ?
            com.ftf.coral.admin.protobuf.ScAccountInfo.getDefaultInstance() : scAccountInfo_;
      }
    }
    /**
     * <code>.ftf.coral.admin.protobuf.ScAccountInfo scAccountInfo = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.ftf.coral.admin.protobuf.ScAccountInfo, com.ftf.coral.admin.protobuf.ScAccountInfo.Builder, com.ftf.coral.admin.protobuf.ScAccountInfoOrBuilder> 
        getScAccountInfoFieldBuilder() {
      if (scAccountInfoBuilder_ == null) {
        scAccountInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.ftf.coral.admin.protobuf.ScAccountInfo, com.ftf.coral.admin.protobuf.ScAccountInfo.Builder, com.ftf.coral.admin.protobuf.ScAccountInfoOrBuilder>(
                getScAccountInfo(),
                getParentForChildren(),
                isClean());
        scAccountInfo_ = null;
      }
      return scAccountInfoBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ftf.coral.admin.protobuf.ScTokenSessionInfo)
  }

  // @@protoc_insertion_point(class_scope:ftf.coral.admin.protobuf.ScTokenSessionInfo)
  private static final com.ftf.coral.admin.protobuf.ScTokenSessionInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.ftf.coral.admin.protobuf.ScTokenSessionInfo();
  }

  public static com.ftf.coral.admin.protobuf.ScTokenSessionInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ScTokenSessionInfo>
      PARSER = new com.google.protobuf.AbstractParser<ScTokenSessionInfo>() {
    @java.lang.Override
    public ScTokenSessionInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ScTokenSessionInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ScTokenSessionInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ScTokenSessionInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.ftf.coral.admin.protobuf.ScTokenSessionInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

