// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scsession.proto

package com.ftf.coral.admin.protobuf;

public interface ScTokenSessionInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ftf.coral.admin.protobuf.ScTokenSessionInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.ftf.coral.admin.protobuf.ScSessionInfo scSessionInfo = 1;</code>
   */
  boolean hasScSessionInfo();
  /**
   * <code>.ftf.coral.admin.protobuf.ScSessionInfo scSessionInfo = 1;</code>
   */
  com.ftf.coral.admin.protobuf.ScSessionInfo getScSessionInfo();
  /**
   * <code>.ftf.coral.admin.protobuf.ScSessionInfo scSessionInfo = 1;</code>
   */
  com.ftf.coral.admin.protobuf.ScSessionInfoOrBuilder getScSessionInfoOrBuilder();

  /**
   * <code>.ftf.coral.admin.protobuf.ScAccountInfo scAccountInfo = 2;</code>
   */
  boolean hasScAccountInfo();
  /**
   * <code>.ftf.coral.admin.protobuf.ScAccountInfo scAccountInfo = 2;</code>
   */
  com.ftf.coral.admin.protobuf.ScAccountInfo getScAccountInfo();
  /**
   * <code>.ftf.coral.admin.protobuf.ScAccountInfo scAccountInfo = 2;</code>
   */
  com.ftf.coral.admin.protobuf.ScAccountInfoOrBuilder getScAccountInfoOrBuilder();
}
