// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wrappers.proto

package com.google.protobuf;

public final class WrappersProto {
  private WrappersProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_DoubleValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_DoubleValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_FloatValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_FloatValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_Int64Value_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_Int64Value_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_UInt64Value_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_UInt64Value_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_Int32Value_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_Int32Value_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_UInt32Value_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_UInt32Value_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_BoolValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_BoolValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_StringValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_StringValue_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_BytesValue_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_protobuf_BytesValue_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016wrappers.proto\022\017google.protobuf\"\034\n\013Dou" +
      "bleValue\022\r\n\005value\030\001 \001(\001\"\033\n\nFloatValue\022\r\n" +
      "\005value\030\001 \001(\002\"\033\n\nInt64Value\022\r\n\005value\030\001 \001(" +
      "\003\"\034\n\013UInt64Value\022\r\n\005value\030\001 \001(\004\"\033\n\nInt32" +
      "Value\022\r\n\005value\030\001 \001(\005\"\034\n\013UInt32Value\022\r\n\005v" +
      "alue\030\001 \001(\r\"\032\n\tBoolValue\022\r\n\005value\030\001 \001(\010\"\034" +
      "\n\013StringValue\022\r\n\005value\030\001 \001(\t\"\033\n\nBytesVal" +
      "ue\022\r\n\005value\030\001 \001(\014B\203\001\n\023com.google.protobu" +
      "fB\rWrappersProtoP\001Z1google.golang.org/pr" +
      "otobuf/types/known/wrapperspb\370\001\001\242\002\003GPB\252\002" +
      "\036Google.Protobuf.WellKnownTypesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_google_protobuf_DoubleValue_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_google_protobuf_DoubleValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_DoubleValue_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_google_protobuf_FloatValue_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_google_protobuf_FloatValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_FloatValue_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_google_protobuf_Int64Value_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_google_protobuf_Int64Value_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_Int64Value_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_google_protobuf_UInt64Value_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_google_protobuf_UInt64Value_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_UInt64Value_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_google_protobuf_Int32Value_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_google_protobuf_Int32Value_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_Int32Value_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_google_protobuf_UInt32Value_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_google_protobuf_UInt32Value_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_UInt32Value_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_google_protobuf_BoolValue_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_google_protobuf_BoolValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_BoolValue_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_google_protobuf_StringValue_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_google_protobuf_StringValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_StringValue_descriptor,
        new java.lang.String[] { "Value", });
    internal_static_google_protobuf_BytesValue_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_google_protobuf_BytesValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_google_protobuf_BytesValue_descriptor,
        new java.lang.String[] { "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
